### ISSUE TITLE
(bug) https error 404

### ISSUE THREAD

**Issue by Delmarcop52** [Kohi-den/extensions-source#230]
### Source information

Anime pahe 14.13

### Source language

English

### Steps to reproduce

1.open animepahe 
2.search kill la kill
3.try to watch the episode 

### Expected behavior

The video is working 

### Actual behavior

![Screenshot_20240911-091427](https://github.com/user-attachments/assets/a9258027-b6e0-4959-b6c6-aec5a015bfe4)

### Aniyomi version

App version: 0.16.4.3-7809 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by JustDigits** [comment]
Try refreshing the anime page to fetch the latest data either by swiping down on the screen or selecting `Refresh` from the three-dot menu (`⋮`) at the top-right corner. According to [this comment on the extension's source code](https://github.com/Kohi-den/extensions-source/blob/6dc7b288e62277237c8567ffe694868a0c27acca/src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt#L143-L144), Animepahe does not provide permanent links to its animes. Navigating to an outdated link would cause the `HTTP 404` error that you're seeing.

As far as I understand, Aniyomi caches some of the anime's data when you first visit it (which is why you can still see the covers of the animes that you've added to your library even without an Internet connection, for example). More likely than not, the episode links were cached too and you just need to fetch the new ones.

**Comment by Delmarcop52** [comment]
Also aniplay is still not working

**Comment by JustDigits** [comment]
Aniplay's status is being tracked by issue #211. While I understand where you're coming from, please try to keep issues aligned with their original topics. I'll try and look into what's causing Aniplay's video list to be empty in the upcoming days. If I find anything worthwhile, I'll be sure to comment it in #211.

Regarding the original issue, did you continue to face any problems with Animepahe, or was the `HTTP 404` error solved after refreshing the anime page?
